name: Auto Unzip ZIP Files

on:
  push:
    branches:
      - main
    paths:
      - '**.zip'

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and unzip all ZIP files
        run: |
          sudo apt-get install -y unzip
          for f in $(find . -name "*.zip"); do
            echo "Unzipping $f"
            unzip -o "$f" -d "${f%.*}"
          done

      - name: Commit unzipped files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Auto-unzipped uploaded ZIP files"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
