name: Auto Unzip ZIP Files

on:
  push:
    branches:
      - main
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Find and unzip all ZIP files
        run: |
          for f in $(find . -name "*.zip"); do
            echo "Unzipping $f"
            unzip -o "$f" -d "${f%.*}"
          done

      - name: Commit unzipped files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-unzipped uploaded ZIP files" || echo "No changes"
          git push
